-- AlterTable
ALTER TABLE "Device" ADD COLUMN     "areaTemp" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "availableMargin" DOUBLE PRECISION,
ADD COLUMN     "fanSpeed" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "moduleTemp" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "operatingCapacity" DOUBLE PRECISION,
ADD COLUMN     "reactivePowerCapacity" DOUBLE PRECISION,
ADD COLUMN     "totalCapacity" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TelemetryRecord" ADD COLUMN     "areaTemp" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "availableMargin" DOUBLE PRECISION,
ADD COLUMN     "fanSpeed" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "moduleTemp" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "operatingCapacity" DOUBLE PRECISION,
ADD COLUMN     "reactivePowerCapacity" DOUBLE PRECISION,
ADD COLUMN     "totalCapacity" DOUBLE PRECISION;
