-- AlterTable
ALTER TABLE "Device" ADD COLUMN "moduleCapacity" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[];

-- AlterTable
ALTER TABLE "TelemetryRecord" ADD COLUMN "moduleCapacity" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[];
